/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HelpRouteImport } from './routes/help'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppBuilderRouteImport } from './routes/app.builder'
import { Route as AppLeaderboardRouteImport } from './routes/app.leaderboard'
import { Route as AppProblemsRouteImport } from './routes/app.problems'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as ProblemsIndexRouteImport } from './routes/problems.index'
import { Route as ProblemsProblemIdRouteImport } from './routes/problems.$problemId'
import { Route as AppLabIndexRouteImport } from './routes/app.lab.index'
import { Route as AppLabProblemIdRouteImport } from './routes/app.lab.$problemId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppBuilderRoute = AppBuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppProblemsRoute = AppProblemsRouteImport.update({
  id: '/problems',
  path: '/problems',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const ProblemsIndexRoute = ProblemsIndexRouteImport.update({
  id: '/problems/',
  path: '/problems/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsProblemIdRoute = ProblemsProblemIdRouteImport.update({
  id: '/problems/$problemId',
  path: '/problems/$problemId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLabIndexRoute = AppLabIndexRouteImport.update({
  id: '/lab/',
  path: '/lab/',
  getParentRoute: () => AppRoute,
} as any)
const AppLabProblemIdRoute = AppLabProblemIdRouteImport.update({
  id: '/lab/$problemId',
  path: '/lab/$problemId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/rules': typeof RulesRoute
  '/timeline': typeof TimelineRoute
  '/app/builder': typeof AppBuilderRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/problems': typeof AppProblemsRoute
  '/app/profile': typeof AppProfileRoute
  '/problems/$problemId': typeof ProblemsProblemIdRoute
  '/app/': typeof AppIndexRoute
  '/problems/': typeof ProblemsIndexRoute
  '/app/lab/$problemId': typeof AppLabProblemIdRoute
  '/app/lab/': typeof AppLabIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/rules': typeof RulesRoute
  '/timeline': typeof TimelineRoute
  '/app/builder': typeof AppBuilderRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/problems': typeof AppProblemsRoute
  '/app/profile': typeof AppProfileRoute
  '/problems/$problemId': typeof ProblemsProblemIdRoute
  '/app': typeof AppIndexRoute
  '/problems': typeof ProblemsIndexRoute
  '/app/lab/$problemId': typeof AppLabProblemIdRoute
  '/app/lab': typeof AppLabIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/rules': typeof RulesRoute
  '/timeline': typeof TimelineRoute
  '/app/builder': typeof AppBuilderRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/problems': typeof AppProblemsRoute
  '/app/profile': typeof AppProfileRoute
  '/problems/$problemId': typeof ProblemsProblemIdRoute
  '/app/': typeof AppIndexRoute
  '/problems/': typeof ProblemsIndexRoute
  '/app/lab/$problemId': typeof AppLabProblemIdRoute
  '/app/lab/': typeof AppLabIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/app'
    | '/contact'
    | '/faq'
    | '/help'
    | '/how-it-works'
    | '/login'
    | '/register'
    | '/rules'
    | '/timeline'
    | '/app/builder'
    | '/app/leaderboard'
    | '/app/problems'
    | '/app/profile'
    | '/problems/$problemId'
    | '/app/'
    | '/problems/'
    | '/app/lab/$problemId'
    | '/app/lab/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/faq'
    | '/help'
    | '/how-it-works'
    | '/login'
    | '/register'
    | '/rules'
    | '/timeline'
    | '/app/builder'
    | '/app/leaderboard'
    | '/app/problems'
    | '/app/profile'
    | '/problems/$problemId'
    | '/app'
    | '/problems'
    | '/app/lab/$problemId'
    | '/app/lab'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/app'
    | '/contact'
    | '/faq'
    | '/help'
    | '/how-it-works'
    | '/login'
    | '/register'
    | '/rules'
    | '/timeline'
    | '/app/builder'
    | '/app/leaderboard'
    | '/app/problems'
    | '/app/profile'
    | '/problems/$problemId'
    | '/app/'
    | '/problems/'
    | '/app/lab/$problemId'
    | '/app/lab/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRouteWithChildren
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  HelpRoute: typeof HelpRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  RulesRoute: typeof RulesRoute
  TimelineRoute: typeof TimelineRoute
  ProblemsProblemIdRoute: typeof ProblemsProblemIdRoute
  ProblemsIndexRoute: typeof ProblemsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/builder': {
      id: '/app/builder'
      path: '/builder'
      fullPath: '/app/builder'
      preLoaderRoute: typeof AppBuilderRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leaderboard': {
      id: '/app/leaderboard'
      path: '/leaderboard'
      fullPath: '/app/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/problems': {
      id: '/app/problems'
      path: '/problems'
      fullPath: '/app/problems'
      preLoaderRoute: typeof AppProblemsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/problems/': {
      id: '/problems/'
      path: '/problems'
      fullPath: '/problems/'
      preLoaderRoute: typeof ProblemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems/$problemId': {
      id: '/problems/$problemId'
      path: '/problems/$problemId'
      fullPath: '/problems/$problemId'
      preLoaderRoute: typeof ProblemsProblemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/lab/': {
      id: '/app/lab/'
      path: '/lab'
      fullPath: '/app/lab/'
      preLoaderRoute: typeof AppLabIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/lab/$problemId': {
      id: '/app/lab/$problemId'
      path: '/lab/$problemId'
      fullPath: '/app/lab/$problemId'
      preLoaderRoute: typeof AppLabProblemIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBuilderRoute: typeof AppBuilderRoute
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppProblemsRoute: typeof AppProblemsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppIndexRoute: typeof AppIndexRoute
  AppLabProblemIdRoute: typeof AppLabProblemIdRoute
  AppLabIndexRoute: typeof AppLabIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBuilderRoute: AppBuilderRoute,
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppProblemsRoute: AppProblemsRoute,
  AppProfileRoute: AppProfileRoute,
  AppIndexRoute: AppIndexRoute,
  AppLabProblemIdRoute: AppLabProblemIdRoute,
  AppLabIndexRoute: AppLabIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AppRoute: AppRouteWithChildren,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  HelpRoute: HelpRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  RulesRoute: RulesRoute,
  TimelineRoute: TimelineRoute,
  ProblemsProblemIdRoute: ProblemsProblemIdRoute,
  ProblemsIndexRoute: ProblemsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
